# Super user permissions required to use Docker
sudo: required
services:
  - docker

before_install:
  - docker build -t mikepod9/docker-react -f Dockerfile.dev .

script:
  - docker run mikepod9/docker-react npm run test -- --coverage
