# Super user permissions required to use Docker
sudo: required
services:
  - docker

before_install:
  - docker build -t mikepod9/docker-react -f Dockerfile.dev .

script:
  - docker run mikepod9/docker-react npm run test_ci

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-279061956885"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
